# Home: добавление комментария
# from selenium import webdriver
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# driver.implicitly_wait(5)
# driver.execute_script("window.scrollBy(0, 600);")
# read_more = driver.find_element_by_css_selector('.post-160>.button')
# read_more.click()
# reviews = driver.find_element_by_class_name('reviews_tab')
# reviews.click()
# five_stars = driver.find_element_by_class_name('star-5')
# five_stars.click()
# your_review = driver.find_element_by_id('comment')
# your_review.send_keys('Nice book!')
# name = driver.find_element_by_id('author')
# name.send_keys('greg')
# email = driver.find_element_by_id('email')
# email.send_keys('greg@yandexd.ru')
# submit = driver.find_element_by_id('submit')
# submit.click()
# driver.quit()